---
# file: tasks/main.yaml

- name: update package cache
  ansible.builtin.apt:
    update_cache: true
  when:
    - ansible_facts["os_family"] == 'Debian'
  tags:
    - dpdk-inst-prerequisites

- name: prerequisites
  ansible.builtin.package:
    name: "{{ packages | flatten(levels=1) }}"
    state: "latest"
  tags:
    - dpdk-inst-prerequisites

<<<<<<< HEAD   (21382c C-Dash: Add rls2610 data)
=======
# To be removed
- name: pip management
  ansible.builtin.file:
    path: "/usr/lib/python3.12/EXTERNALLY-MANAGED"
    state: "absent"
  tags:
    - common-inst-pip


- name: meson (dpdk)
  ansible.builtin.pip:
    name:
      - "meson==0.64.1"
    state: "forcereinstall"
  environment:
    ANSIBLE_SKIP_CONFLICT_CHECK: 1
  tags:
    - dpdk-inst-prerequisites

>>>>>>> CHANGE (041f4c infra: 2n-gnr)
- name: multiple DPDK versions
  include_tasks: "deploy_block.yaml"
  loop: "{{ dpdk_version }}"
  tags:
    - dpdk-inst
