---
# file: tasks/main.yaml

- name: update package cache (apt)
  apt:
    update_cache: true
    cache_valid_time: 3600
  when:
    - ansible_facts["distribution"]|lower == 'ubuntu'
  tags:
    - mellanox-inst-drivers

- name: prerequisites
  package:
    name: "{{ packages | flatten(levels=1) }}"
    state: "latest"
  tags:
    - mellanox-inst-drivers

- name: check presence of mellanox
  shell: "lspci | grep Mellanox | awk '{print $1}'"
  register: mellanox_pcis
  failed_when: false
  changed_when: false
  tags:
    - mellanox-inst-drivers

- name: get mellanox ofed driver versions
  set_fact:
    ofed: "{{ mellanox_compatibility_matrix[mellanox_matrix]['ofed'] }}"
  when: >
    mellanox_pcis.stdout_lines | length > 0 and
    mellanox_matrix is defined
  tags:
    - mellanox-inst-drivers

- name: driver mellanox
  import_tasks: ofed.yaml
  when: >
    mellanox_pcis.stdout_lines | length > 0 and
    mellanox_matrix is defined
  tags:
    - mellanox-inst-drivers
