---
# file: tasks/main.yaml

- name: update repositories cache
  ansible.builtin.apt:
    update_cache: true
  when:
    - ansible_facts["os_family"] == 'Debian'
  tags:
    - common-inst-prerequisites

- name: prerequisites
  ansible.builtin.package:
    name: "{{ packages | flatten(levels=1) }}"
    state: "latest"
  tags:
    - common-inst-prerequisites

