# Copyright (c) 2022 Cisco and/or its affiliates.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

*** Settings ***
| Resource | resources/libraries/robot/shared/default.robot
|
| Force Tags | 1_NODE_SINGLE_LINK_TOPO | 2_NODE_SINGLE_LINK_TOPO
| ... | 3_NODE_SINGLE_LINK_TOPO
| ... | PERFTEST | HW_ENV | NDRPDR | NIC_Intel-X710 | TREX | ETH | IP4FWD
| ... | N2N | IP4BASE | UDP | UDP_PPS | TG_DRV_IGB_UIO | SCALE | HOSTS_1024
| ... | ethip4udp-ip4base-h1024-p63-s64512-pps-tg
|
| Suite Setup | Setup suite topology interfaces with no DUT | performance_tg_nic
| Suite Teardown | Tear down suite | performance
| Test Setup | Start Test Export
| Test Teardown | Tear down test raw | performance
|
| Test Template | Local Template
|
| # TODO CSIT-1765: Unify suite Documentation.
| Documentation | **PPS on lightweight UDP transactions with L1 cross connect**
| ... |
| ... | - **[Top] Network Topologies:** TG-TG 1-node circular topology \
| ... | with single links between nodes.
| ... |
| ... | - **[Enc] Packet Encapsulations:** Eth-IPv4 for L1 cross connect patch.
| ... |
| ... | - **[Ver] TG verification:** TG finds and reports throughput NDR (Non \
| ... | Drop Rate) with zero packet loss tolerance and throughput PDR \
| ... | (Partial Drop Rate) with non-zero packet loss tolerance (LT) \
| ... | expressed in percentage of packets transmitted. NDR and PDR are \
| ... | discovered for different Ethernet L2 frame sizes using MLRsearch \
| ... | library.
| ... | Test packets are generated by TG on links to TG. \
| ... | TG traffic profile contains client and server ASTF programs, \
| ... | generating packets containing Ethernet header, IPv4 header, \
| ... | UDP header and static payload. \
| ... | MAC addresses are matching MAC addresses of the TG node interfaces.
| ... |
| ... | - **[Ref] Applicable standard specifications:** RFC2544.

*** Variables ***
| ${nic_name}= | Intel-X710
| ${nic_pfs}= | 2
| ${osi_layer}= | L7
| ${overhead}= | ${0}
# Scale settings
| ${n_hosts}= | ${1024}
| ${n_ports}= | ${63}
| ${transaction_scale}= | ${${n_hosts} * ${n_ports}}
| ${packets_per_transaction_and_direction}= | ${ASTF_N_DATA_FRAMES}
# Traffic profile:
| ${traffic_profile}= | trex-astf-ethip4udp-${n_hosts}h-pps
| ${transaction_type}= | udp_pps
| ${disable_latency}= | ${True}

*** Keywords ***
| Local Template
| | [Documentation]
| | ... | - **[Cfg]** TG runs L1 cross connect config.
| | ... | - **[Ver]** Measure NDR and PDR values using MLRsearch algorithm.
| |
| | ... | *Arguments:*
| | ... | - frame_size - Framesize in Bytes in integer or string (IMIX_v4_1).
| | ... | Type: integer, string
| |
| | [Arguments] | ${frame_size}
| |
| | Set Test Variable | \${frame_size}
| |
| | Given Set Max Rate And Jumbo
| | Then Find NDR and PDR intervals using optimized search

*** Test Cases ***
| 120B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 120B
| | frame_size=${120}

| 121B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 121B
| | frame_size=${121}

| 122B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 122B
| | frame_size=${122}

| 123B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 123B
| | frame_size=${123}

| 124B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 124B
| | frame_size=${124}

| 125B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 125B
| | frame_size=${125}

| 126B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 126B
| | frame_size=${126}

| 127B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 127B
| | frame_size=${127}

| 128B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 128B
| | frame_size=${128}

| 129B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 129B
| | frame_size=${129}

| 130B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 130B
| | frame_size=${130}

| 131B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 131B
| | frame_size=${131}

| 132B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 132B
| | frame_size=${132}

| 133B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 133B
| | frame_size=${133}

| 134B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 134B
| | frame_size=${134}

| 135B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 135B
| | frame_size=${135}

| 136B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 136B
| | frame_size=${136}

| 137B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 137B
| | frame_size=${137}

| 138B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 138B
| | frame_size=${138}

| 139B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 139B
| | frame_size=${139}

| 140B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 140B
| | frame_size=${140}

| 141B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 141B
| | frame_size=${141}

| 142B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 142B
| | frame_size=${142}

| 143B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 143B
| | frame_size=${143}

| 144B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 144B
| | frame_size=${144}

| 145B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 145B
| | frame_size=${145}

| 146B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 146B
| | frame_size=${146}

| 147B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 147B
| | frame_size=${147}

| 148B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 148B
| | frame_size=${148}

| 149B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 149B
| | frame_size=${149}

| 150B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 150B
| | frame_size=${150}

| 1518B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 1518B
| | frame_size=${1518}

| 9000B--ethip4udp-ip4base-h1024-p63-s64512-pps-tg-ndrpdr
| | [Tags] | 9000B
| | frame_size=${9000}
