# Copyright (c) 2022 Cisco and/or its affiliates.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

*** Settings ***
| Resource | resources/libraries/robot/shared/default.robot
|
| Force Tags | 1_NODE_SINGLE_LINK_TOPO | 2_NODE_SINGLE_LINK_TOPO
| ... | 3_NODE_SINGLE_LINK_TOPO
| ... | PERFTEST | HW_ENV | NDRPDR | NIC_Intel-X710 | TREX | ETH | IP4FWD
| ... | IP4BASE | N2N | UDP | UDP_PPS | TG_DRV_IGB_UIO | SCALE | HOSTS_262144
| ... | ethip4udp-ip4base-h262144-p63-s16515072-pps-tg
|
| Suite Setup | Setup suite topology interfaces with no DUT | performance_tg_nic
| Suite Teardown | Tear down suite | performance
| Test Setup | Start Test Export
| Test Teardown | Tear down test raw | performance
|
| Test Template | Local Template
|
| Documentation | **PPS on lightweight UDP transactions with L1 cross connect**
| ... |
| ... | - **[Top] Network Topologies:** TG-TG 1-node circular topology \
| ... | with single links between nodes.
| ... |
| ... | - **[Enc] Packet Encapsulations:** Eth-IPv4 for L1 cross connect patch.
| ... |
| ... | - **[Ver] TG verification:** TG finds and reports throughput NDR (Non \
| ... | Drop Rate) with zero packet loss tolerance and throughput PDR \
| ... | (Partial Drop Rate) with non-zero packet loss tolerance (LT) \
| ... | expressed in percentage of packets transmitted. NDR and PDR are \
| ... | discovered for different Ethernet L2 frame sizes using MLRsearch \
| ... | library.
| ... | Test packets are generated by TG on links to TG. \
| ... | TG traffic profile contains client and server ASTF programs, \
| ... | generating packets containing Ethernet header, IPv4 header, \
| ... | TCP header and static payload. \
| ... | MAC addresses are matching MAC addresses of the TG node interfaces.
| ... |
| ... | - **[Ref] Applicable standard specifications:** RFC2544.

*** Variables ***
| ${nic_name}= | Intel-X710
| ${nic_pfs}= | 2
| ${osi_layer}= | L7
| ${overhead}= | ${0}
# Scale settings
| ${n_hosts}= | ${262144}
| ${n_ports}= | ${63}
| ${transaction_scale}= | ${${n_hosts} * ${n_ports}}
| ${packets_per_transaction_and_direction}= | ${ASTF_N_DATA_FRAMES}
# Traffic profile:
| ${traffic_profile}= | trex-astf-ethip4udp-${n_hosts}h-pps
| ${transaction_type}= | udp_pps
| ${disable_latency}= | ${True}

*** Keywords ***
| Local Template
| | [Documentation]
| | ... | - **[Cfg]** TG runs L1 cross connect config.
| | ... | - **[Ver]** Measure NDR and PDR values using MLRsearch algorithm.
| |
| | ... | *Arguments:*
| | ... | - frame_size - Framesize in Bytes in integer or string (IMIX_v4_1).
| | ... | Type: integer, string
| |
| | [Arguments] | ${frame_size}
| |
| | Set Test Variable | \${frame_size}
| |
| | Given Set Max Rate And Jumbo
| | Then Find NDR and PDR intervals using optimized search

*** Test Cases ***
| 90B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 90B
| | frame_size=${90}

| 120B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 120B
| | frame_size=${120}

| 150B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 150B
| | frame_size=${150}

| 180B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 180B
| | frame_size=${180}

| 210B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 210B
| | frame_size=${210}

| 240B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 240B
| | frame_size=${240}

| 270B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 270B
| | frame_size=${270}

| 300B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 300B
| | frame_size=${300}

| 330B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 330B
| | frame_size=${330}

| 360B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 360B
| | frame_size=${360}

| 390B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 390B
| | frame_size=${390}

| 420B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 420B
| | frame_size=${420}

| 450B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 450B
| | frame_size=${450}

| 480B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 480B
| | frame_size=${480}

| 510B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 510B
| | frame_size=${510}

| 540B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 540B
| | frame_size=${540}

| 570B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 570B
| | frame_size=${570}

| 600B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 600B
| | frame_size=${600}

| 630B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 630B
| | frame_size=${630}

| 660B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 660B
| | frame_size=${660}

| 690B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 690B
| | frame_size=${690}

| 720B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 720B
| | frame_size=${720}

| 750B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 750B
| | frame_size=${750}

| 780B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 780B
| | frame_size=${780}

| 810B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 810B
| | frame_size=${810}

| 840B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 840B
| | frame_size=${840}

| 870B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 870B
| | frame_size=${870}

| 900B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 900B
| | frame_size=${900}

| 930B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 930B
| | frame_size=${930}

| 960B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 960B
| | frame_size=${960}

| 990B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 990B
| | frame_size=${990}

| 1020B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1020B
| | frame_size=${1020}

| 1050B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1050B
| | frame_size=${1050}

| 1080B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1080B
| | frame_size=${1080}

| 1110B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1110B
| | frame_size=${1110}

| 1140B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1140B
| | frame_size=${1140}

| 1170B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1170B
| | frame_size=${1170}

| 1200B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1200B
| | frame_size=${1200}

| 1230B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1230B
| | frame_size=${1230}

| 1260B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1260B
| | frame_size=${1260}

| 1290B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1290B
| | frame_size=${1290}

| 1320B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1320B
| | frame_size=${1320}

| 1350B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1350B
| | frame_size=${1350}

| 1380B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1380B
| | frame_size=${1380}

| 1410B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1410B
| | frame_size=${1410}

| 1440B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1440B
| | frame_size=${1440}

| 1470B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1470B
| | frame_size=${1470}

| 1518B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 1518B
| | frame_size=${1518}

| 9000B--ethip4udp-ip4base-h262144-p63-s16515072-pps-tg-ndrpdr
| | [Tags] | 9000B
| | frame_size=${9000}
