"""
Operational data
================

The operational data reflect the current status of HFR and all jobs (runs) and
testbeds managed by it.

The Structure
-------------

[
    Run(
        node=str,
        # See the documentation in 'job_configuration.py' for Run.
        conf=RunConf(
            workflow=str,
            # The item 'inputs' depends on the GHA workflow specification,
            # example is for the report workflow.
            inputs={
                "job_type": str,
                "dut": str,
                "node": str,
                "branch": str,
                "suite_gen_params": str
            },
            name=str,
            ref=str
        ),
        # See the documentation in 'intf_tb.py' for Testbed.
        tb=Testbed(
            name=str,
            node=str,
            tg=dict,
            status=str,
            job=str,
            run_id=str
        ),
        data=RunData(
            gha_data=dict,
            hfr_id=str,
            hfr_status=str,
            nr_of_runs=str
        )
    ),

    ...
]

RunData
.......

gha_data:
- Data generated by GHA.

hfr_id:
- Run ID set by HFR.

hfr_status:
- Set by HFR:
    - queued,
    - started,
    - running,
    - finished,
    - canceled.

nr_of_runs:
- Number of runs of the same run, it is used when the run is canceled and should
  be re-run again.

"""


import csv
import logging
import os

from dataclasses import dataclass, asdict
from json import dump, load

from hfr.app_configuration import AppConfiguration
from hfr.constants import Constants as C
from hfr.run_configuration import RunConfiguration
from hfr.run_configuration import RunConf
from hfr.intf_tb import Testbed


@dataclass
class RunData:
    """Current status of a run.
    """
    gha_data: dict
    hfr_id: str
    hfr_status: str
    nr_of_runs: int


@dataclass
class Run:
    """One item in the list of operational data. It keeps all data connected to
    one run.
    """
    node: str
    conf: RunConf
    tb: Testbed
    data: RunData


class OperData:
    """Operational data.
    """

    RUN_DATA_DEFAULTS = dict(
        gha_data = dict(),
        hfr_id = str(),
        hfr_status = C.HFR_RUN_INITIAL_STATUS,
        nr_of_runs = 0
    )

    def __init__(self, app_conf: AppConfiguration, runs: RunConfiguration):
        """Initialize the operational data.
        """
        self._app_conf = app_conf
        self._runs = runs

        logging.info("Initializing the operational data...")
        if self._app_conf.keep_old_oper_data:
            self._data = self._from_json_file()
            if not self._data:
                self._initialize()
        else:
            self._initialize()
        self.to_json_file()
        logging.info("Done.")

    def _from_json_file(self):
        """Read the operational data from the JSON file and deserialize it.
        """

        # Read JSON file
        try:
            with(open(self._app_conf.path_to_oper, "rt") as fr):
                j_data = load(fr)
        except IOError as err:
            raise RuntimeError(
                f"Not possible to read from the file "
                f"'{self._app_conf.path_to_oper}'\n {err}"
            )

        # Deserialize
        return [
            Run(
                node=itm["node"],
                conf=RunConf(**itm["run"]),
                tb=Testbed(**itm["tb"]),
                data=RunData(**itm["data"]))
            for itm in j_data
        ]

    def to_json_file(self):
        """Serialize the operational data and write it to the JSON file.
        """
        # Serialize:
        s_data = [asdict(itm) for itm in self._data]

        # Write JSON file:
        try:
            directory = self._app_conf.path_to_oper.rsplit("/", maxsplit=1)[0]
            if not os.path.exists(directory):
                os.makedirs(directory)
            with(open(self._app_conf.path_to_oper, "wt") as fw):
                dump(s_data, fw)
        except IOError as err:
            raise RuntimeError(
                f"Not possible to write to the file "
                f"'{self._app_conf.path_to_oper}'\n {err}"
            )

    def to_csv_file(self):
        """Write the selected items from the operational data to a CSV file.
        """

        # Pick and organize the items from operational data.
        j_data = list()
        for itm in self._data:
            tb = itm.tb.name if itm.tb else str()
            gha = itm.data.gha_data if itm.data.gha_data else None
            j_data.append({
                "DUT": itm.conf.inputs.get("dut", str()),
                "Node": itm.node,
                "Job type": itm.conf.inputs.get("job_type", str()),
                "Testbed": tb,
                "Run": itm.conf.name,
                "HFR ID": itm.data.hfr_id,
                "HFR status": itm.data.hfr_status,
                "Run URL": gha["html_url"] if gha else str(),
                "Run status": gha["status"] if gha else str(),
                "Run conclusion": gha["conclusion"] if gha else str(),
                "Log": \
                    f"{C.LOG_URL}/{itm.conf.name}/{gha['id'] if gha else str()}"
            })

        # Write to CSV file.
        try:
            with open(self._app_conf.path_to_csv, "w", newline="") as fw:
                writer = csv.DictWriter(fw, fieldnames=j_data[0].keys())
                writer.writeheader()
                writer.writerows(j_data)
        except IOError as err:
            raise RuntimeError(
                f"Not possible to write to the file "
                f"'{self._app_conf.path_to_csv}'\n {err}"
            )

    def _initialize(self):
        """Initialize the operational data.
        - Create the structure with all specified runs.
        """
        self._data = list()
        for node, runs in self._runs.runs.items():
            for run in runs:
                self._data.append(Run(
                    node=node,
                    conf=run,
                    tb=None,
                    data=RunData(**OperData.RUN_DATA_DEFAULTS)
                ))

    @property
    def data(self):
        """Returns the operational data.
        :rtype: list
        """
        return self._data
