"""
Operational data
================

The operational data reflect the current status of HFR and all jobs (runs) and
testbeds managed by it.

The Structure
-------------

[
    Run(
        node=str,
        # See the documentation in 'job_configuration.py' for Run.
        conf=RunConf(
            workflow=str,
            # The item 'inputs' depends on the GHA workflow specification,
            # example is for the report workflow.
            inputs={
                "job_type": str,
                "dut": str,
                "node": str,
                "branch": str,
                "suite_gen_params": str
            }
        ),
        # See the documentation in 'intf_tb.py' for Testbed.
        tb=Testbed(
            name=str,
            node=str,
            tg=dict,
            status=str,
            job=str,
            run_id=str
        ),
        data=RunData(
            gha_name=str,
            gha_id=str,
            gha_data=dict,
            gha_status=str,
            gha_conclusion=str,
            hfr_status=str
        )
    ),

    ...
]

RunData
.......

gha_name:
- The name of the run set by HFR and used by GHA.

rgha_id:
- Generated and set by HFR to identify it in GHA.

gha_data:
- Data generated by GHA.

gha_status:
- Status of the run in GHA.

gha_conclusion:
- The result of the run set by GHA when the run is finished.

hfr_status:
- Set by HFR:
    - queued,
    - started,
    - running,
    - finished,
    - canceled.

"""


import logging
import os

from dataclasses import dataclass, asdict
from json import dump, load

from hfr.app_configuration import AppConfiguration
from hfr.constants import Constants as C
from hfr.job_configuration import JobConfiguration
from hfr.job_configuration import RunConf
from hfr.intf_tb import Testbed


@dataclass
class RunData:
    """Current status of a run.
    """
    gha_name: str
    gha_id: str
    gha_data: dict
    gha_status: str
    gha_conclusion: str
    hfr_id: str
    hfr_status: str


@dataclass
class Run:
    """One item in the list of operational data. It keeps all data connected to
    one run.
    """
    node: str
    conf: RunConf
    tb: Testbed
    data: RunData


class OperData:
    """Operational data.
    """

    RUN_DATA_DEFAULTS = dict(
        gha_name = str(),
        gha_id = str(),
        gha_data = dict(),
        gha_status = str(),
        gha_conclusion = str(),
        hfr_id = str(),
        hfr_status = C.HFR_RUN_INITIAL_STATUS
    )

    def __init__(self, app_conf: AppConfiguration, jobs: JobConfiguration):
        """Initialize the operational data.
        """
        self._app_conf = app_conf
        self._jobs = jobs

        logging.info("Initializing the operationa data...")
        if self._app_conf.keep_old_oper_data:
            self._data = self._from_json_file()
            if not self._data:
                self._initialize()
        else:
            self._initialize()
        self.to_json_file()
        logging.info("Done.")

    def _from_json_file(self):
        """Read the operational data from the JSON file and deserialize it.
        """

        # Read JSON file
        try:
            with(open(self._app_conf.path_to_oper, "rt") as fr):
                j_data = load(fr)
        except IOError as err:
            raise RuntimeError(
                f"Not possible to read from the file "
                f"'{self._app_conf.path_to_oper}'\n {err}"
            )

        # Deserialize
        return [
            Run(
                node=itm["node"],
                conf=RunConf(**itm["run"]),
                tb=Testbed(**itm["tb"]),
                data=RunData(**itm["data"]))
            for itm in j_data
        ]

    def to_csv_file(self):
        """
        """
        raise NotImplementedError

    def to_json_file(self):
        """Serialize the operational data and write it to the JSON file.
        """
        # Serialize:
        s_data = [asdict(itm) for itm in self._data]

        # Write JSON file:
        try:
            directory = self._app_conf.path_to_oper.rsplit("/", maxsplit=1)[0]
            if not os.path.exists(directory):
                os.makedirs(directory)
            with(open(self._app_conf.path_to_oper, "wt") as fw):
                dump(s_data, fw)
        except IOError as err:
            raise RuntimeError(
                f"Not possible to write to the file "
                f"'{self._app_conf.path_to_oper}'\n {err}"
            )

    def _initialize(self):
        """Initialize the operational data.
        - Create the structure with all specified jobs.
        """
        self._data = list()
        self._add_jobs()

    def _add_jobs(self):
        """Add specified jobs to the operational data.
        - No data, only jobs as they are defined in the configuration.
        """
        for node, runs in self._jobs.runs.items():
            for run in runs:
                self._data.append(Run(
                    node=node,
                    conf=run,
                    tb=None,
                    data=RunData(**OperData.RUN_DATA_DEFAULTS)
                ))

    @property
    def data(self):
        """Returns the operational data.
        :rtype: list
        """
        return self._data
