# Copyright (c) 2020 Cisco and/or its affiliates.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

*** Settings ***
| Resource | resources/libraries/robot/shared/default.robot
| Resource | resources/libraries/robot/ip/geneve.robot
| Resource | resources/libraries/robot/shared/traffic.robot
|
| Force Tags | 2_NODE_SINGLE_LINK_TOPO | DEVICETEST | HW_ENV | DCR_ENV | SCAPY
| ... | NIC_Virtual | ETH | L2BDMACSTAT | ENCAP | GENEVE_L2MODE | GEN4_4TUN
| ... | SCALE | DRV_VFIO_PCI | TEST
| ... | RXQ_SIZE_0 | TXQ_SIZE_0
| ... | ethip4--ethip4udpgeneve-4tun-l2bdmacstat
|
| Suite Setup | Setup suite topology interfaces | scapy
| Test Setup | Setup test
| Test Teardown | Tear down test | packet_trace
|
| Test Template | Local Template
|
| Documentation | *L2BD with GENEVE L2 mode test cases*
|
| ... | *[Top] Network Topologies:* TG-DUT1-TG 2-node circular topology
| ... | with single links between nodes.
| ... | *[Enc] Packet Encapsulations:* Eth-IPv4-UDP for L2 switching in one direction and ....
| ... | *[Cfg] DUT configuration:* DUT1 is configured with IPv4 routing and
| ... | one static IPv4 /18 route entries.
| ... | DUT1 is tested with ${nic_name}.\
| ... | *[Ver] TG verification:* TG finds and reports throughput NDR (Non Drop\
| ... | Rate) with zero packet loss tolerance and throughput PDR (Partial Drop\
| ... | Rate) with non-zero packet loss tolerance (LT) expressed in percentage\
| ... | of packets transmitted. NDR and PDR are discovered for different\
| ... | Ethernet L2 frame sizes using MLRsearch library.\
| ... | Test packets are generated by TG on links to DUT1. TG traffic profile
| ... | contains two L3 flow-groups (flow-group per direction, 1 flow per
| ... | flow-group) with all packets containing Ethernet header, IPv4 header
| ... | with IP protocol=61 and static payload. MAC addresses are matching MAC
| ... | addresses of the TG node interfaces.
| ... | *[Ref] Applicable standard specifications:* RFC2544.

*** Variables ***
| @{plugins_to_enable}= | dpdk_plugin.so | geneve_plugin.so
| ${crypto_type}= | ${None}
| ${nic_name}= | virtual
| ${nic_driver}= | vfio-pci
| ${nic_rxq_size}= | 0
| ${nic_txq_size}= | 0
| ${nic_pfs}= | 2
| ${nic_vfs}= | 0
| ${osi_layer}= | L2
| ${overhead}= | ${0}
# L2 settings
| ${bd_id}= | ${1}
# IP settings
#| ${tg_if1_ip4}= | 10.0.0.1
#| ${tg_if1_mask}= | ${24}
#| ${tg_if2_ip4}= | 10.0.0.1
#| ${tg_if2_mask}= | ${32}
# GENEVE settings
| ${gen_mode}= | L2
| &{gen_tun1}=
| ... | local=20.0.0.1 | remote=300.0.0.1 | vni=${10}
| ... | src_mac=02:00:00:10:20:30 | dst_mac=02:00:00:10:20:31
| ... | src_ip=11.1.0.1 | dst_ip=11.0.0.1
| &{gen_tun2}=
| ... | local=21.0.0.1 | remote=310.0.0.1 | vni=${20}
| ... | src_mac=12:00:00:10:20:31 | dst_mac=12:00:00:10:20:32
| ... | src_ip=12.1.0.1 | dst_ip=12.0.0.1
| &{gen_tun3}=
| ... | local=22.0.0.1 | remote=320.0.0.1 | vni=${30}
| ... | src_mac=22:00:00:10:20:32 | dst_mac=22:00:00:10:20:33
| ... | src_ip=13.0.0.0 | dst_ip=13.0.0.1
| &{gen_tun4}=
| ... | local=23.0.0.1 | remote=330.0.0.1 | vni=${40}
| ... | src_mac=32:00:00:10:20:33 | dst_mac=32:00:00:10:20:34
| ... | src_ip=14.0.0.0 | dst_ip=14.0.0.1
#| ${dest_mask}= | ${24}

*** Keywords ***
| Local Template
| |
| | [Documentation]
| | ... | [Cfg] DUT runs GENEVE ${gen_mode} mode configuration.
| | ... | Each DUT uses ${phy_cores} physical core(s) for worker threads.
| | ... | [Ver] Measure NDR and PDR values using MLRsearch algorithm.\
| |
| | ... | *Arguments:*
| | ... | - frame_size - Framesize in Bytes in integer or string (IMIX_v4_1).
| | ... | Type: integer, string
| | ... | - phy_cores - Number of physical cores. Type: integer
| | ... | - rxq - Number of RX queues, default value: ${None}. Type: integer
| |
| | [Arguments] | ${frame_size} | ${phy_cores} | ${rxq}=${None}
| |
| | Set Test Variable | \${frame_size}
| | ${geneve_tunnels}= | Create List
| | ... | ${gen_tun1} | ${gen_tun2} | ${gen_tun3} | ${gen_tun4}
| | Set Test Variable | ${geneve_tunnels}
| |
| | Given Set Max Rate And Jumbo
| | And Add worker threads to all DUTs | ${phy_cores} | ${rxq}
| | And Pre-initialize layer driver | ${nic_driver}
| | And Apply startup configuration on all VPP DUTs
| | When Initialize layer driver | ${nic_driver}
| | And Initialize layer interface
| | And Initialize GENEVE ${gen_mode} mode in circular topology
| | Then Send IP packet and verify GENEVE encapcapsulation in received packets
| | ... | ${tg} | ${TG_pf1}[0] | ${TG_pf2}[0] | ${TG_pf1_mac}[0]
| | ... | @{geneve_tunnels}

*** Test Cases ***
| 64B-1c-ethip4--ethip4udpgeneve-4tun-l2bdmacstat-ndrpdr
| | [Tags] | 64B
| | frame_size=${64} | phy_cores=${0}
