# Copyright (c) 2017 Cisco and/or its affiliates.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

*** Settings ***
| Resource | resources/libraries/robot/performance.robot
| Resource | resources/libraries/robot/snat.robot
| Resource | resources/libraries/robot/traffic.robot
| ...
| Force Tags | 3_NODE_SINGLE_LINK_TOPO | PERFTEST | HW_ENV | NDRPDRDISC
| ... | NIC_Intel-X520-DA2 | ETH | IP4FWD | FEATURE | SNAT | THIS
| ...
| Suite Setup | 3-node Performance Suite Setup with DUT's NIC model
| ... | L3 | Intel-X520-DA2
| Suite Teardown | 3-node Performance Suite Teardown
| ...
| Test Setup | Performance test setup
| ...
| Documentation | *SNAT performance test cases*
| ...
| ... | *High level description*
| ...
| ... | - NDR and PDR tests
| ... | - 3-node topology, TG-DUT1-DUT2-TG, SNAT is enabled between DUTs.
| ... | - Cores / threads: 1t1c and 2t2c
| ... | - Framesize: 66B, 1518B, IMIX
| ... | - Packet: ETH / IP(src, dst) / UDP(src_port, dst_port) / load
| ... | - scale: src: 1 user, 10 users, 100 users, ..., 4000 up to the memory
| ... |   limit; 15 ports per user
| ...
| ... | *Low level description*
| ...
| ... | *[Top] Network Topologies:* TG-DUT1-DUT2-TG 3-node circular topology
| ... | with single links between nodes.
| ... | *[Enc] Packet Encapsulations:* Eth-IPv4 for IPv4 routing.
| ... | *[Cfg] DUT configuration:* DUT1 and DUT2 are configured with IPv4
| ... | routing and two static IPv4 /24 route entries. DUT1 and DUT2 tested with
| ... | 2p10GE NIC X520 Niantic by Intel.
| ... | *[Ver] TG verification:* TG finds and reports throughput NDR (Non Drop
| ... | Rate) with zero packet loss tolerance or throughput PDR (Partial Drop
| ... | Rate) with non-zero packet loss tolerance (LT) expressed in percentage
| ... | of packets transmitted. NDR and PDR are discovered for different
| ... | Ethernet L2 frame sizes using either binary search or linear search
| ... | algorithms with configured starting rate and final step that determines
| ... | throughput measurement resolution. Test packets are generated by TG on
| ... | links to DUTs. TG traffic profile contains two L3 flow-groups
| ... | (flow-group per direction, 253 flows per flow-group) with all packets
| ... | containing Ethernet header, IPv4 header with IP protocol=61 and static
| ... | payload. MAC addresses are matching MAC addresses of the TG node
| ... | interfaces.
| ... | *[Ref] Applicable standard specifications:* RFC2544.
| ...
| ... | *TODO List*
| ... | - update VPP Running Configuration with
| ... |   snat {
| ... |     deterministic
| ... |   }
| ... |   It is necessary if we want to use T-rex in stateless mode.
| ... | - configuration of VPP, new kewords:
| ... |   - set int snat in int_in out int_out
| ... |   - snat deterministic add in IP/range out IP/range
| ... |   - set snat workers (nice to have)
| ... | - Traffic generator:
| ... |   - add ports - the best way is to re-implement tg scripts using Python
| ... |     objects to define streams (Bigger effort but we will have a
| ... |     universal solution to the future).

*** Variables ***
# X520-DA2 bandwidth limit
| ${s_limit} | ${10000000000}

*** Test Cases ***
| tc01-66B-1t1c-ethip4-ip4base-snat-1u-1p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 66 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1u-1p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | ${66}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-1p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc02-66B-1t1c-ethip4-ip4base-snat-1u-1p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 66 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1u-1p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable | ${66}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-1p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}

| tc05-66B-1t1c-ethip4-ip4base-snat-10u-15p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 66 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-10u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | ${66}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-10u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc06-66B-1t1c-ethip4-ip4base-snat-10u-15p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 66 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-10u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable | ${66}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-10u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}

| tc11-1518B-1t1c-ethip4-ip4base-snat-1u-1p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 1518 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1u-1p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | ${1518}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-1p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc12-1518B-1t1c-ethip4-ip4base-snat-1u-1p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 1518 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1u-1p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable | ${1518}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-1p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}

| tc15-1518B-1t1c-ethip4-ip4base-snat-10u-15p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 1518 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-10u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | ${1518}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-10u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc16-1518B-1t1c-ethip4-ip4base-snat-10u-15p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 1518 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-10u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable | ${1518}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-10u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}

| tc21-IMIX-1t1c-ethip4-ip4base-snat-1u-1p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for IMIX frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1u-1p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | IMIX_v4_1
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-1p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc22-IMIX-1t1c-ethip4-ip4base-snat-1u-1p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for IMIX frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1u-1p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable | IMIX_v4_1
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-1p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}

| tc25-IMIX-1t1c-ethip4-ip4base-snat-10u-15p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for IMIX frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-10u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | IMIX_v4_1
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-10u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc26-IMIX-1t1c-ethip4-ip4base-snat-10u-15p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for IMIX frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-10u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable |IMIX_v4_1
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-10u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}


























#| tc01-66B-1t1c-ethip4-ip4base-snat-1u-1p-ndrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find NDR for 66 Byte frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-1u-1p
#| | ...
#| | [Tags] | 1T1C | STHREAD | NDRDISC
#| | ...
#| | ${framesize}= | Set Variable | ${66}
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
#| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-1p | ${min_rate} | ${max_rate}
#| | ... | ${threshold}
#
#| tc02-66B-1t1c-ethip4-ip4base-snat-1u-1p-pdrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find PDR for 66 Byte frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-1u-1p
#| | ...
#| | [Tags] | 1T1C | STHREAD | PDRDISC
#| | ...
#| | ${framesize}= | Set Variable | ${66}
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
#| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-1p | ${min_rate} | ${max_rate}
#| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
#| | ... | ${perf_pdr_loss_acceptance_type}

| tc03-66B-1t1c-ethip4-ip4base-snat-1u-15p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 66 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | ${66}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc04-66B-1t1c-ethip4-ip4base-snat-1u-15p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 66 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable | ${66}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}

#| tc05-66B-1t1c-ethip4-ip4base-snat-10u-15p-ndrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find NDR for 66 Byte frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-10u-15p
#| | ...
#| | [Tags] | 1T1C | STHREAD | NDRDISC
#| | ...
#| | ${framesize}= | Set Variable | ${66}
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
#| | ... | ${binary_max} | 3-node-IPv4-SNAT-10u-15p | ${min_rate} | ${max_rate}
#| | ... | ${threshold}
#
#| tc06-66B-1t1c-ethip4-ip4base-snat-10u-15p-pdrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find PDR for 66 Byte frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-10u-15p
#| | ...
#| | [Tags] | 1T1C | STHREAD | PDRDISC
#| | ...
#| | ${framesize}= | Set Variable | ${66}
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
#| | ... | ${binary_max} | 3-node-IPv4-SNAT-10u-15p | ${min_rate} | ${max_rate}
#| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
#| | ... | ${perf_pdr_loss_acceptance_type}

| tc07-66B-1t1c-ethip4-ip4base-snat-100u-15p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 66 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-100u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | ${66}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-100u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc08-66B-1t1c-ethip4-ip4base-snat-100u-15p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 66 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-100u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable | ${66}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-100u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}

| tc09-66B-1t1c-ethip4-ip4base-snat-1000u-15p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 66 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1000u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | ${66}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-100u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc10-66B-1t1c-ethip4-ip4base-snat-1000u-15p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 66 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1000u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable | ${66}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1000u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}





#| tc11-1518B-1t1c-ethip4-ip4base-snat-1u-1p-ndrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find NDR for 1518 Byte frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-1u-1p
#| | ...
#| | [Tags] | 1T1C | STHREAD | NDRDISC
#| | ...
#| | ${framesize}= | Set Variable | ${1518}
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
#| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-1p | ${min_rate} | ${max_rate}
#| | ... | ${threshold}
#
#| tc12-1518B-1t1c-ethip4-ip4base-snat-1u-1p-pdrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find PDR for 1518 Byte frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-1u-1p
#| | ...
#| | [Tags] | 1T1C | STHREAD | PDRDISC
#| | ...
#| | ${framesize}= | Set Variable | ${1518}
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
#| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-1p | ${min_rate} | ${max_rate}
#| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
#| | ... | ${perf_pdr_loss_acceptance_type}

| tc13-1518B-1t1c-ethip4-ip4base-snat-1u-15p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 1518 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | ${1518}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc14-1518B-1t1c-ethip4-ip4base-snat-1u-15p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 1518 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable | ${1518}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}

#| tc15-1518B-1t1c-ethip4-ip4base-snat-10u-15p-ndrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find NDR for 1518 Byte frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-10u-15p
#| | ...
#| | [Tags] | 1T1C | STHREAD | NDRDISC
#| | ...
#| | ${framesize}= | Set Variable | ${1518}
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
#| | ... | ${binary_max} | 3-node-IPv4-SNAT-10u-15p | ${min_rate} | ${max_rate}
#| | ... | ${threshold}
#
#| tc16-1518B-1t1c-ethip4-ip4base-snat-10u-15p-pdrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find PDR for 1518 Byte frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-10u-15p
#| | ...
#| | [Tags] | 1T1C | STHREAD | PDRDISC
#| | ...
#| | ${framesize}= | Set Variable | ${1518}
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
#| | ... | ${binary_max} | 3-node-IPv4-SNAT-10u-15p | ${min_rate} | ${max_rate}
#| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
#| | ... | ${perf_pdr_loss_acceptance_type}

| tc17-1518B-1t1c-ethip4-ip4base-snat-100u-15p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 1518 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-100u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | ${1518}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-100u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc18-1518B-1t1c-ethip4-ip4base-snat-100u-15p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 1518 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-100u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable | ${1518}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-100u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}

| tc19-1518B-1t1c-ethip4-ip4base-snat-1000u-15p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 1518 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1000u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | ${1518}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-100u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc20-1518B-1t1c-ethip4-ip4base-snat-1000u-15p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 1518 Byte frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1000u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable | ${1518}
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1000u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}







#| tc21-IMIX-1t1c-ethip4-ip4base-snat-1u-1p-ndrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find NDR for IMIX frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-1u-1p
#| | ...
#| | [Tags] | 1T1C | STHREAD | NDRDISC
#| | ...
#| | ${framesize}= | Set Variable | IMIX_v4_1
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
#| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-1p | ${min_rate} | ${max_rate}
#| | ... | ${threshold}
#
#| tc22-IMIX-1t1c-ethip4-ip4base-snat-1u-1p-pdrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find PDR for IMIX frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-1u-1p
#| | ...
#| | [Tags] | 1T1C | STHREAD | PDRDISC
#| | ...
#| | ${framesize}= | Set Variable | IMIX_v4_1
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
#| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-1p | ${min_rate} | ${max_rate}
#| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
#| | ... | ${perf_pdr_loss_acceptance_type}

| tc23-IMIX-1t1c-ethip4-ip4base-snat-1u-15p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for IMIX frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | IMIX_v4_1
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc24-IMIX-1t1c-ethip4-ip4base-snat-1u-15p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for IMIX frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable | IMIX_v4_1
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}

#| tc25-IMIX-1t1c-ethip4-ip4base-snat-10u-15p-ndrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find NDR for IMIX frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-10u-15p
#| | ...
#| | [Tags] | 1T1C | STHREAD | NDRDISC
#| | ...
#| | ${framesize}= | Set Variable | IMIX_v4_1
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
#| | ... | ${binary_max} | 3-node-IPv4-SNAT-10u-15p | ${min_rate} | ${max_rate}
#| | ... | ${threshold}
#
#| tc26-IMIX-1t1c-ethip4-ip4base-snat-10u-15p-pdrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find PDR for IMIX frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-10u-15p
#| | ...
#| | [Tags] | 1T1C | STHREAD | PDRDISC
#| | ...
#| | ${framesize}= | Set Variable |IMIX_v4_1
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
#| | ... | ${binary_max} | 3-node-IPv4-SNAT-10u-15p | ${min_rate} | ${max_rate}
#| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
#| | ... | ${perf_pdr_loss_acceptance_type}

| tc27-IMIX-1t1c-ethip4-ip4base-snat-100u-15p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for IMIX frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-100u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | IMIX_v4_1
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-100u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc28-IMIX-1t1c-ethip4-ip4base-snat-100u-15p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for IMIX frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-100u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable | IMIX_v4_1
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-100u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}

| tc29-IMIX-1t1c-ethip4-ip4base-snat-1000u-15p-ndrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for IMIX frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1000u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | NDRDISC
| | ...
| | ${framesize}= | Set Variable | IMIX_v4_1
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find NDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-100u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold}

| tc30-IMIX-1t1c-ethip4-ip4base-snat-1000u-15p-pdrdisc
| | [Documentation]
| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
| | ... | 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for IMIX frames using binary search start at 10GE
| | ... | linerate, step 100kpps.
| | ...
| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
| | ... | 3-node-IPv4-SNAT-1000u-15p
| | ...
| | [Tags] | 1T1C | STHREAD | PDRDISC
| | ...
| | ${framesize}= | Set Variable | IMIX_v4_1
| | ${min_rate}= | Set Variable | ${100000}
| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
| | ${binary_min}= | Set Variable | ${min_rate}
| | ${binary_max}= | Set Variable | ${max_rate}
| | ${threshold}= | Set Variable | ${min_rate}
| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
| | And Add PCI devices to DUTs from 3-node single link topology
| | And Add No Multi Seg to all DUTs
| | And Add SNAT to all DUTs
| | And Apply startup configuration on all VPP DUTs
| | When SNAT is initialized in a 3-node circular topology for performance test
| | Then Find PDR using binary search and pps | ${framesize} | ${binary_min}
| | ... | ${binary_max} | 3-node-IPv4-SNAT-1000u-15p | ${min_rate} | ${max_rate}
| | ... | ${threshold} | ${perf_pdr_loss_acceptance}
| | ... | ${perf_pdr_loss_acceptance_type}








#| tc01-66B-1t1c-ethip4-ip4base-snat-1u-1p-ndrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find NDR for 66 Byte frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-1u-1p
#| | ...
#| | [Tags] | 1T1C | STHREAD | NDRDISC | THIS
#| | ...
#| | ${framesize}= | Set Variable | ${66}
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Fail
#
#
#| tc01-66B-1t1c-ethip4-ip4base-snat-1u-15p-ndrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find NDR for 66 Byte frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-1u-15p
#| | ...
#| | [Tags] | 1T1C | STHREAD | NDRDISC | THIS
#| | ...
#| | ${framesize}= | Set Variable | ${66}
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Fail
#
#
#| tc01-66B-1t1c-ethip4-ip4base-snat-10u-15p-ndrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find NDR for 66 Byte frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-10u-15p
#| | ...
#| | [Tags] | 1T1C | STHREAD | NDRDISC | THIS
#| | ...
#| | ${framesize}= | Set Variable | ${66}
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Fail
#
#
#| tc01-66B-1t1c-ethip4-ip4base-snat-100u-15p-ndrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find NDR for 66 Byte frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-100u-15p
#| | ...
#| | [Tags] | 1T1C | STHREAD | NDRDISC | THIS
#| | ...
#| | ${framesize}= | Set Variable | ${66}
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Fail
#
#
#| tc01-66B-1t1c-ethip4-ip4base-snat-1000u-15p-ndrdisc
#| | [Documentation]
#| | ... | [Cfg] DUT runs IPv4 routing config with 1 thread, 1 phy core, \
#| | ... | 1 receive queue per NIC port.
#| | ... | [Ver] Find NDR for 66 Byte frames using binary search start at 10GE
#| | ... | linerate, step 100kpps.
#| | ...
#| | [Teardown] | Performance test teardown | ${min_rate}pps | ${framesize}
#| | ... | 3-node-IPv4-SNAT-1000u-15p
#| | ...
#| | [Tags] | 1T1C | STHREAD | NDRDISC | THIS
#| | ...
#| | ${framesize}= | Set Variable | ${66}
#| | ${min_rate}= | Set Variable | ${100000}
#| | ${max_rate}= | Calculate pps | ${s_limit} | ${framesize}
#| | ${binary_min}= | Set Variable | ${min_rate}
#| | ${binary_max}= | Set Variable | ${max_rate}
#| | ${threshold}= | Set Variable | ${min_rate}
#| | Given Add '1' worker threads and rxqueues '1' in 3-node single-link topo
#| | And Add PCI devices to DUTs from 3-node single link topology
#| | And Add No Multi Seg to all DUTs
#| | And Add SNAT to all DUTs
#| | And Apply startup configuration on all VPP DUTs
#| | When SNAT is initialized in a 3-node circular topology for performance test
#| | Fail
