# Copyright (c) 2016 Cisco and/or its affiliates.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

*** Settings ***
| Resource | resources/libraries/robot/performance.robot
| Library | resources.libraries.python.Cop
| Library | resources.libraries.python.IPv4Setup.Dut | ${nodes['DUT1']} | WITH NAME | dut1_v4
| Library | resources.libraries.python.IPv4Setup.Dut | ${nodes['DUT2']} | WITH NAME | dut2_v4
| Force Tags | 3_NODE_SINGLE_LINK_TOPO | PERFTEST | HW_ENV | PERFTEST_SHORT
| ...        | NIC_Intel-X520-DA2
| Suite Setup | 3-node Performance Suite Setup with DUT's NIC model
| ... | L3 | Intel-X520-DA2
| Suite Teardown | 3-node Performance Suite Teardown
| Test Setup | Setup all DUTs before test
| Test Teardown | Run Keyword | Remove startup configuration of VPP from all DUTs
| Documentation | *Reference NDR throughput verify test cases*
| ...
| ... | Reference throughput test suite uses a physical 3-node topology TG -
| ... | DUT1 - DUT2 - TG with one link between connected nodes. Each node is a
| ... | standalone server compute node. In short performance tests, TG verifies
| ... | DUTs' throughput at ref-NDR (reference Non Drop Rate) with zero packet
| ... | loss tolerance. Ref-NDR value is periodically updated acording to
| ... | formula: ref-NDR = 0.9x NDR, where NDR is found in RFC2544 long
| ... | performance tests for the same DUT confiiguration. Test packets are
| ... | generated by TG on links to DUTs. TG traffic profile contains two L3
| ... | flow-groups (flow-group per direction, 253 flows per flow-group) with
| ... | all packets containing Ethernet header, IPv4 header with IP protocol=61
| ... | and random payload. MAC addresses are matching MAC addresses of the TG
| ... | node interfaces.  Baseline packet throughput performance of DUTs
| ... | configured with IPv4 routing and IPv4 security COP whitelist ingress
| ... | filtering applied on links TG - DUT1 and DUT2 - TG, is tested with two
| ... | static IPv4 /24 route entries and additional IPv4 FIB table with index 1
| ... | with whitelist /24 filter entry. DUT1 and DUT2 tested with 2p10GE NIC
| ... | X520 Niantic by Intel.

*** Test Cases ***
| TC01: Verify 64B ref-NDR at 2x 3.5Mpps - DUT IPv4 whitelist - 1thread 1core 1rxq
| | [Documentation]
| | ... | Verify ref-NDR for 64 Byte frames using single trial throughput
| | ... | test. DUT runs IPv4 routing and whitelist filters config with
| | ... | 1 thread, 1 phy core, 1 receive queue per NIC port.
| | [Tags] | 1_THREAD_NOHTT_RXQUEUES_1 | SINGLE_THREAD
| | ${framesize}= | Set Variable | 64
| | ${duration}= | Set Variable | 10
| | ${rate}= | Set Variable | 3.5mpps
| | Given Add '1' worker threads and rxqueues '1' without HTT to all DUTs
| | And   Add all PCI devices to all DUTs
| | And   Add No Multi Seg to all DUTs
| | And   Apply startup configuration on all VPP DUTs
| | When  IPv4 forwarding initialized in a 3-node circular topology
| | And   Add fib table | ${dut1} | 10.10.10.0 | 24 | 1 | local
| | And   Add fib table | ${dut2} | 20.20.20.0 | 24 | 1 | local
| | And   COP Add whitelist Entry | ${dut1} | ${dut1_if1} | ip4 | 1
| | And   COP Add whitelist Entry | ${dut2} | ${dut2_if2} | ip4 | 1
| | And   COP interface enable or disable | ${dut1} | ${dut1_if1} | enable
| | And   COP interface enable or disable | ${dut2} | ${dut2_if2} | enable
| | Then  Traffic should pass with no loss | ${duration} | ${rate}
| | ...                                    | ${framesize} | 3-node-IPv4

| TC02: Verify 1518B ref-NDR at 2x 812.74kpps - DUT IPv4 whitelist - 1thread 1core 1rxq
| | [Documentation]
| | ... | Verify ref-NDR for 1518 Byte frames using single trial throughput
| | ... | test. DUT runs IPv4 routing and whitelist filters config with
| | ... | 1 thread, 1 phy core, 1 receive queue per NIC port.
| | [Tags] | 1_THREAD_NOHTT_RXQUEUES_1 | SINGLE_THREAD
| | ${framesize}= | Set Variable | 1518
| | ${duration}= | Set Variable | 10
| | ${rate}= | Set Variable | 812743pps
| | Given Add '1' worker threads and rxqueues '1' without HTT to all DUTs
| | And   Add all PCI devices to all DUTs
| | And   Add No Multi Seg to all DUTs
| | And   Apply startup configuration on all VPP DUTs
| | When  IPv4 forwarding initialized in a 3-node circular topology
| | And   Add fib table | ${dut1} | 10.10.10.0 | 24 | 1 | local
| | And   Add fib table | ${dut2} | 20.20.20.0 | 24 | 1 | local
| | And   COP Add whitelist Entry | ${dut1} | ${dut1_if1} | ip4 | 1
| | And   COP Add whitelist Entry | ${dut2} | ${dut2_if2} | ip4 | 1
| | And   COP interface enable or disable | ${dut1} | ${dut1_if1} | enable
| | And   COP interface enable or disable | ${dut2} | ${dut2_if2} | enable
| | Then  Traffic should pass with no loss | ${duration} | ${rate}
| | ...                                    | ${framesize} | 3-node-IPv4

| TC03: Verify 9000B ref-NDR at 2x 138.58kpps - DUT IPv4 whitelist - 1thread 1core 1rxq
| | [Documentation]
| | ... | Verify ref-NDR for 9000 Byte frames using single trial throughput
| | ... | test. DUT runs IPv4 routing and whitelist filters config with
| | ... | 1 thread, 1 phy core, 1 receive queue per NIC port.
| | [Tags] | 1_THREAD_NOHTT_RXQUEUES_1 | SINGLE_THREAD
| | ${framesize}= | Set Variable | 9000
| | ${duration}= | Set Variable | 10
| | ${rate}= | Set Variable | 138580pps
| | Given Add '1' worker threads and rxqueues '1' without HTT to all DUTs
| | And   Add all PCI devices to all DUTs
| | And   Apply startup configuration on all VPP DUTs
| | When  IPv4 forwarding initialized in a 3-node circular topology
| | And   Add fib table | ${dut1} | 10.10.10.0 | 24 | 1 | local
| | And   Add fib table | ${dut2} | 20.20.20.0 | 24 | 1 | local
| | And   COP Add whitelist Entry | ${dut1} | ${dut1_if1} | ip4 | 1
| | And   COP Add whitelist Entry | ${dut2} | ${dut2_if2} | ip4 | 1
| | And   COP interface enable or disable | ${dut1} | ${dut1_if1} | enable
| | And   COP interface enable or disable | ${dut2} | ${dut2_if2} | enable
| | Then Traffic should pass with no loss | ${duration} | ${rate}
| | ...                                   | ${framesize} | 3-node-IPv4

| TC04: Verify 64B ref-NDR at 2x 6.6Mpps - DUT IPv4 whitelist - 2thread 2core 1rxq
| | [Documentation]
| | ... | Verify ref-NDR for 64 Byte frames using single trial throughput
| | ... | test. DUT runs IPv4 routing and whitelist filters config with
| | ... | 2 threads, 2 phy cores, 1 receive queue per NIC port.
| | [Tags] | 2_THREAD_NOHTT_RXQUEUES_1 | MULTI_THREAD
| | ${framesize}= | Set Variable | 64
| | ${duration}= | Set Variable | 10
| | ${rate}= | Set Variable | 6.6mpps
| | Given Add '2' worker threads and rxqueues '1' without HTT to all DUTs
| | And   Add all PCI devices to all DUTs
| | And   Add No Multi Seg to all DUTs
| | And   Apply startup configuration on all VPP DUTs
| | When  IPv4 forwarding initialized in a 3-node circular topology
| | And   Add fib table | ${dut1} | 10.10.10.0 | 24 | 1 | local
| | And   Add fib table | ${dut2} | 20.20.20.0 | 24 | 1 | local
| | And   COP Add whitelist Entry | ${dut1} | ${dut1_if1} | ip4 | 1
| | And   COP Add whitelist Entry | ${dut2} | ${dut2_if2} | ip4 | 1
| | And   COP interface enable or disable | ${dut1} | ${dut1_if1} | enable
| | And   COP interface enable or disable | ${dut2} | ${dut2_if2} | enable
| | Then Traffic should pass with no loss | ${duration} | ${rate}
| | ...                                   | ${framesize} | 3-node-IPv4

| TC05: Verify 1518B ref-NDR at 2x 812.74kpps - DUT IPv4 whitelist - 2thread 2core 1rxq
| | [Documentation]
| | ... | Verify ref-NDR for 1518 Byte frames using single trial throughput
| | ... | test. DUT runs IPv4 routing and whitelist filters config with
| | ... | 2 threads, 2 phy cores, 1 receive queue per NIC port.
| | [Tags] | 2_THREAD_NOHTT_RXQUEUES_1 | MULTI_THREAD
| | ${framesize}= | Set Variable | 1518
| | ${duration}= | Set Variable | 10
| | ${rate}= | Set Variable | 812743pps
| | Given Add '2' worker threads and rxqueues '1' without HTT to all DUTs
| | And   Add all PCI devices to all DUTs
| | And   Add No Multi Seg to all DUTs
| | And   Apply startup configuration on all VPP DUTs
| | When  IPv4 forwarding initialized in a 3-node circular topology
| | And   Add fib table | ${dut1} | 10.10.10.0 | 24 | 1 | local
| | And   Add fib table | ${dut2} | 20.20.20.0 | 24 | 1 | local
| | And   COP Add whitelist Entry | ${dut1} | ${dut1_if1} | ip4 | 1
| | And   COP Add whitelist Entry | ${dut2} | ${dut2_if2} | ip4 | 1
| | And   COP interface enable or disable | ${dut1} | ${dut1_if1} | enable
| | And   COP interface enable or disable | ${dut2} | ${dut2_if2} | enable
| | Then Traffic should pass with no loss | ${duration} | ${rate}
| | ...                                   | ${framesize} | 3-node-IPv4

| TC06: Verify 9000B ref-NDR at 2x 138.58kpps - DUT IPv4 whitelist - 2thread 2core 1rxq
| | [Documentation]
| | ... | Verify ref-NDR for 9000 Byte frames using single trial throughput
| | ... | test. DUT runs IPv4 routing and whitelist filters config with
| | ... | 2 threads, 2 phy cores, 1 receive queue per NIC port.
| | [Tags] | 2_THREAD_NOHTT_RXQUEUES_1 | MULTI_THREAD
| | ${framesize}= | Set Variable | 9000
| | ${duration}= | Set Variable | 10
| | ${rate}= | Set Variable | 138580pps
| | Given Add '2' worker threads and rxqueues '1' without HTT to all DUTs
| | And   Add all PCI devices to all DUTs
| | And   Apply startup configuration on all VPP DUTs
| | When  IPv4 forwarding initialized in a 3-node circular topology
| | And   Add fib table | ${dut1} | 10.10.10.0 | 24 | 1 | local
| | And   Add fib table | ${dut2} | 20.20.20.0 | 24 | 1 | local
| | And   COP Add whitelist Entry | ${dut1} | ${dut1_if1} | ip4 | 1
| | And   COP Add whitelist Entry | ${dut2} | ${dut2_if2} | ip4 | 1
| | And   COP interface enable or disable | ${dut1} | ${dut1_if1} | enable
| | And   COP interface enable or disable | ${dut2} | ${dut2_if2} | enable
| | Then Traffic should pass with no loss | ${duration} | ${rate}
| | ...                                   | ${framesize} | 3-node-IPv4

| TC07: Verify 64B ref-NDR at 2x 10.0Mpps - DUT IPv4 whitelist - 4threads 4cores 2rxq
| | [Documentation]
| | ... | Verify ref-NDR for 64 Byte frames using single trial throughput
| | ... | test. DUT runs IPv4 routing and whitelist filters config with
| | ... | 1 thread, 1 phy core, 1 receive queue per NIC port.
| | [Tags] | 4_THREAD_NOHTT_RXQUEUES_2 | MULTI_THREAD
| | ${framesize}= | Set Variable | 64
| | ${duration}= | Set Variable | 10
| | ${rate}= | Set Variable | 10.0mpps
| | Given Add '4' worker threads and rxqueues '2' without HTT to all DUTs
| | And   Add all PCI devices to all DUTs
| | And   Add No Multi Seg to all DUTs
| | And   Apply startup configuration on all VPP DUTs
| | When  IPv4 forwarding initialized in a 3-node circular topology
| | And   Add fib table | ${dut1} | 10.10.10.0 | 24 | 1 | local
| | And   Add fib table | ${dut2} | 20.20.20.0 | 24 | 1 | local
| | And   COP Add whitelist Entry | ${dut1} | ${dut1_if1} | ip4 | 1
| | And   COP Add whitelist Entry | ${dut2} | ${dut2_if2} | ip4 | 1
| | And   COP interface enable or disable | ${dut1} | ${dut1_if1} | enable
| | And   COP interface enable or disable | ${dut2} | ${dut2_if2} | enable
| | Then Traffic should pass with no loss | ${duration} | ${rate}
| | ...                                   | ${framesize} | 3-node-IPv4

| TC08: Verify 1518B ref-NDR at 2x 812.74kpps - DUT IPv4 whitelist - 4threads 4cores 2rxq
| | [Documentation]
| | ... | Verify ref-NDR for 1518 Byte frames using single trial throughput
| | ... | test. DUT runs IPv4 routing and whitelist filters config with
| | ... | 1 thread, 1 phy core, 1 receive queue per NIC port.
| | [Tags] | 4_THREAD_NOHTT_RXQUEUES_2 | MULTI_THREAD
| | ${framesize}= | Set Variable | 1518
| | ${duration}= | Set Variable | 10
| | ${rate}= | Set Variable | 812743pps
| | Given Add '4' worker threads and rxqueues '2' without HTT to all DUTs
| | And   Add all PCI devices to all DUTs
| | And   Add No Multi Seg to all DUTs
| | And   Apply startup configuration on all VPP DUTs
| | When  IPv4 forwarding initialized in a 3-node circular topology
| | And   Add fib table | ${dut1} | 10.10.10.0 | 24 | 1 | local
| | And   Add fib table | ${dut2} | 20.20.20.0 | 24 | 1 | local
| | And   COP Add whitelist Entry | ${dut1} | ${dut1_if1} | ip4 | 1
| | And   COP Add whitelist Entry | ${dut2} | ${dut2_if2} | ip4 | 1
| | And   COP interface enable or disable | ${dut1} | ${dut1_if1} | enable
| | And   COP interface enable or disable | ${dut2} | ${dut2_if2} | enable
| | Then Traffic should pass with no loss | ${duration} | ${rate}
| | ...                                   | ${framesize} | 3-node-IPv4

| TC09: Verify 9000B ref-NDR at 2x 138.58kpps - DUT IPv4 whitelist - 4threads 4cores 2rxq
| | [Documentation]
| | ... | Verify ref-NDR for 9000 Byte frames using single trial throughput
| | ... | test. DUT runs IPv4 routing and whitelist filters config with
| | ... | 1 thread, 1 phy core, 1 receive queue per NIC port.
| | [Tags] | 4_THREAD_NOHTT_RXQUEUES_2 | MULTI_THREAD
| | ${framesize}= | Set Variable | 9000
| | ${duration}= | Set Variable | 10
| | ${rate}= | Set Variable | 138580pps
| | Given Add '4' worker threads and rxqueues '2' without HTT to all DUTs
| | And   Add all PCI devices to all DUTs
| | And   Apply startup configuration on all VPP DUTs
| | When  IPv4 forwarding initialized in a 3-node circular topology
| | And   Add fib table | ${dut1} | 10.10.10.0 | 24 | 1 | local
| | And   Add fib table | ${dut2} | 20.20.20.0 | 24 | 1 | local
| | And   COP Add whitelist Entry | ${dut1} | ${dut1_if1} | ip4 | 1
| | And   COP Add whitelist Entry | ${dut2} | ${dut2_if2} | ip4 | 1
| | And   COP interface enable or disable | ${dut1} | ${dut1_if1} | enable
| | And   COP interface enable or disable | ${dut2} | ${dut2_if2} | enable
| | Then Traffic should pass with no loss | ${duration} | ${rate}
| | ...                                   | ${framesize} | 3-node-IPv4
