---
# file: roles/kernel_vm/tasks/main.yaml

- name: backup remote initramfs modules
  ansible.builtin.copy:
    src: /etc/initramfs-tools/modules
    dest: /tmp/initramfs_modules.bkp
    remote_src: true
  ignore_errors: true
  register: __initramfs_modules_backuped
  tags:
    - kernel-inst-image

- name: backup remote initramfs resume config
  ansible.builtin.copy:
    src: /etc/initramfs-tools/conf.d/resume
    dest: /tmp/initramfs-resume.bkp
    remote_src: true
  ignore_errors: true
  register: __initramfs_resume_backuped
  tags:
    - kernel-inst-image

- name: update remote initramfs modules
  ansible.builtin.copy:
    src: ../files/initramfs_modules
    dest: /etc/initramfs-tools/modules
  tags:
    - kernel-inst-image

- name: update remote initramfs resume config
  ansible.builtin.copy:
    src: ../files/initramfs_resume
    dest: /etc/initramfs-tools/conf.d/resume
  tags:
    - kernel-inst-image

- name: create target kernel dir
  ansible.builtin.file:
    path: /opt/boot
    state: directory
  tags:
    - kernel-inst-image

- name: build initrd image
  ansible.builtin.shell: "update-initramfs -k {{ ansible_facts['kernel'] }} -c -b /opt/boot"
  tags:
    - kernel-inst-image

- name: copy corresponding kernel img
  ansible.builtin.copy:
    src: "/boot/vmlinuz-{{ ansible_facts['kernel'] }}"
    dest: "/opt/boot/vmlinuz-{{ ansible_facts['kernel'] }}"
    remote_src: true
  tags:
    - kernel-inst-image

- name: restore remote initramfs modules
  ansible.builtin.copy:
    src: /tmp/initramfs_modules.bkp
    dest: /etc/initramfs-tools/modules
    remote_src: true
  ignore_errors: true
  when: __initramfs_modules_backuped is not skipped
  tags:
    - kernel-inst-image

- name: remove remote backup initramfs modules
  ansible.builtin.file:
    path: /tmp/initramfs_modules.bkp
    state: absent
  when: __initramfs_modules_backuped is not skipped
  tags:
    - kernel-inst-image

- name: restore remote initramfs resume config
  ansible.builtin.copy:
    src: /tmp/initramfs-resume.bkp
    dest: /etc/initramfs-tools/conf.d/resume
    remote_src: true
  ignore_errors: true
  when: __initramfs_resume_backuped is not skipped
  tags:
    - kernel-inst-image

- name: remove remote backup initramfs resume config
  ansible.builtin.file:
    path: /tmp/initramfs-resume.bkp
    state: "absent"
  when: __initramfs_resume_backuped is not skipped
  tags:
    - kernel-inst-image
