# Copyright (c) 2018 Cisco and/or its affiliates.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

*** Settings ***
| Resource | resources/libraries/robot/performance/performance_setup.robot
| Resource | resources/libraries/robot/dpdk/default.robot
| Library | resources.libraries.python.DPDK.DPDKTools
| Force Tags | 3_NODE_SINGLE_LINK_TOPO | HW_ENV | PERFTEST | NDRPDRDISC | 1NUMA
| ... | NIC_Intel-X520-DA2 | DPDK | ETH | L2XCFWD | BASE
| Suite Setup | Set up DPDK 3-node performance topology with DUT's NIC model
| ... | L2 | Intel-X520-DA2
| Suite Teardown | Tear down DPDK 3-node performance topology
| Documentation | *RFC2544: Pkt throughput IPv4 routing test cases*
| ...
| ... | *[Top] Network Topologies:* TG-DUT1-DUT2-TG 3-node circular topology\
| ... | with single links between nodes.
| ... | *[Enc] Packet Encapsulations:* Eth-IPv4 for L2 frame forwarding.
| ... | *[Cfg] DUT configuration:* DUT1 and DUT2 run the DPDK testpmd\
| ... | application and use the io forwarding mode. DUT1 and DUT2 tested with\
| ... | 2p10GE NIC X520 Niantic by Intel.
| ... | *[Ver] TG verification:* TG finds and reports throughput NDR (Non Drop\
| ... | Rate) with zero packet loss tolerance or throughput PDR (Partial Drop\
| ... | Rate) with non-zero packet loss tolerance (LT) expressed in percentage\
| ... | of packets transmitted. NDR and PDR are discovered for different\
| ... | Ethernet L2 frame sizes using either binary search or linear search\
| ... | algorithms with configured starting rate and final step that determines\
| ... | throughput measurement resolution. Test packets are generated by TG on\
| ... | links to DUTs. TG traffic profile contains two L3 flow-groups\
| ... | (flow-group per direction, 254 flows per flow-group) with all packets\
| ... | containing Ethernet header, IPv4 header with IP protocol=61 and static\
| ... | payload. MAC addresses are matching MAC addresses of the TG node\
| ... | interfaces.
| ... | *[Ref] Applicable standard specifications:* RFC2544.

*** Variables ***
# Traffic profile:
| ${traffic_profile}= | trex-sl-3n-ethip4-ip4src254
# Trex minimal pps per stream is 9000.
| ${min_rate}= | ${100000}
# Search is terminated when width is less than the following value.
| ${threshold}= | ${100000}

*** Keywords ***
| Find NDR for eth-l2xcbase-testpmd
| | [Arguments]
| | ... | ${wt} | ${rxq} | ${framesize}
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with ${wt} thread,\
| | ... | ${wt} phy core, ${rxq} receive queue per NIC port.
| | ... | [Ver] Find NDR for ${framesize} Byte frames\
| | ... | using binary search, max 10GE linerate, step ${threshold}pps.
| | ...
| | # Set test variables
| | ${max_rate}= | Calculate pps | ${i_x520_da2_uni_max} | ${framesize}
| | ${get_framesize}= | Get Frame Size | ${framesize}
| | ${jumbo}= | Set Variable If | ${get_framesize} < ${1522} | no | yes
| | When Start L2FWD '${wt}' worker threads and '${rxq}' rxqueues with jumbo frames '${jumbo}'
| | Then Find NDR using binary search and pps | ${framesize} | ${min_rate}
| | ... | ${max_rate} | ${traffic_profile} | ${min_rate} | ${max_rate} | ${threshold}

| Find PDR for eth-l2xcbase-testpmd
| | [Arguments]
| | ... | ${wt} | ${rxq} | ${framesize}
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with ${wt} thread,\
| | ... | ${wt} phy core, ${rxq} receive queue per NIC port.
| | ... | [Ver] Find PDR for ${framesize} Byte frames\
| | ... | using binary search, max 10GE linerate, step ${threshold}pps.
| | ...
| | # Set test variables
| | ${max_rate}= | Calculate pps | ${i_x520_da2_uni_max} | ${framesize}
| | ${get_framesize}= | Get Frame Size | ${framesize}
| | ${jumbo}= | Set Variable If | ${get_framesize} < ${1522} | no | yes
| | When Start L2FWD '${wt}' worker threads and '${rxq}' rxqueues with jumbo frames '${jumbo}'
| | Then Find PDR using binary search and pps | ${framesize} | ${min_rate}
| | ... | ${max_rate} | ${traffic_profile} | ${min_rate} | ${max_rate} | ${threshold}
| | ... | ${perf_pdr_loss_acceptance} | ${perf_pdr_loss_acceptance_type}

*** Test Cases ***
| tc01-64B-1t1c-eth-l2xcbase-testpmd-ndrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 1 thread,\
| | ... | 1 phy core, 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 64 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 64B | 1T1C | STHREAD | NDRDISC
| | ...
| | [Template] | Find NDR for eth-l2xcbase-testpmd
| | wt=1 | rxq=1 | framesize=${64}

| tc02-64B-1t1c-eth-l2xcbase-testpmd-pdrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 1 thread,\
| | ... | 1 phy core, 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 64 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 64B | 1T1C | STHREAD | PDRDISC | SKIP_PATCH
| | ...
| | [Template] | Find PDR for eth-l2xcbase-testpmd
| | wt=1 | rxq=1 | framesize=${64}

| tc03-1518B-1t1c-eth-l2xcbase-testpmd-ndrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 1 thread,\
| | ... | 1 phy core, 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 1518 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 1518B | 1T1C | STHREAD | NDRDISC
| | ...
| | [Template] | Find NDR for eth-l2xcbase-testpmd
| | wt=1 | rxq=1 | framesize=${1518}

| tc04-1518B-1t1c-eth-l2xcbase-testpmd-pdrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 1 thread,\
| | ... | 1 phy core, 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 1518 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 1518B | 1T1C | STHREAD | PDRDISC | SKIP_PATCH
| | ...
| | [Template] | Find PDR for eth-l2xcbase-testpmd
| | wt=1 | rxq=1 | framesize=${1518}

| tc05-9000B-1t1c-eth-l2xcbase-testpmd-ndrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 1 thread,\
| | ... | 1 phy core, 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 9000 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 9000B | 1T1C | STHREAD | NDRDISC
| | ...
| | [Template] | Find NDR for eth-l2xcbase-testpmd
| | wt=1 | rxq=1 | framesize=${9000}

| tc06-9000B-1t1c-eth-l2xcbase-testpmd-pdrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 1 thread,\
| | ... | 1 phy core, 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 9000 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 9000B | 1T1C | STHREAD | PDRDISC | SKIP_PATCH
| | ...
| | [Template] | Find PDR for eth-l2xcbase-testpmd
| | wt=1 | rxq=1 | framesize=${9000}

| tc07-64B-2t2c-eth-l2xcbase-testpmd-ndrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 2 thread,\
| | ... | 2 phy core, 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 64 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 64B | 2T2C | MTHREAD | NDRDISC
| | ...
| | [Template] | Find NDR for eth-l2xcbase-testpmd
| | wt=2 | rxq=1 | framesize=${64}

| tc08-64B-2t2c-eth-l2xcbase-testpmd-pdrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 2 thread,\
| | ... | 2 phy core, 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 64 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 64B | 2T2C | MTHREAD | PDRDISC | SKIP_PATCH
| | ...
| | [Template] | Find PDR for eth-l2xcbase-testpmd
| | wt=2 | rxq=1 | framesize=${64}

| tc09-1518B-2t2c-eth-l2xcbase-testpmd-ndrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 2 thread,\
| | ... | 2 phy core, 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 1518 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 1518B | 2T2C | MTHREAD | NDRDISC | SKIP_PATCH
| | ...
| | [Template] | Find NDR for eth-l2xcbase-testpmd
| | wt=2 | rxq=1 | framesize=${1518}

| tc10-1518B-2t2c-eth-l2xcbase-testpmd-pdrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 2 thread,\
| | ... | 2 phy core, 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 1518 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 1518B | 2T2C | MTHREAD | PDRDISC | SKIP_PATCH
| | ...
| | [Template] | Find PDR for eth-l2xcbase-testpmd
| | wt=2 | rxq=1 | framesize=${1518}

| tc11-9000B-2t2c-eth-l2xcbase-testpmd-ndrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 2 thread,\
| | ... | 2 phy core, 1 receive queue per NIC port.
| | ... | [Ver] Find NDR for 9000 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 9000B | 2T2C | MTHREAD | NDRDISC | SKIP_PATCH
| | ...
| | [Template] | Find NDR for eth-l2xcbase-testpmd
| | wt=2 | rxq=1 | framesize=${9000}

| tc12-9000B-2t2c-eth-l2xcbase-testpmd-pdrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 2 thread,\
| | ... | 2 phy core, 1 receive queue per NIC port.
| | ... | [Ver] Find PDR for 9000 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 9000B | 2T2C | MTHREAD | PDRDISC | SKIP_PATCH
| | ...
| | [Template] | Find PDR for eth-l2xcbase-testpmd
| | wt=2 | rxq=1 | framesize=${9000}

| tc13-64B-4t4c-eth-l2xcbase-testpmd-ndrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 4 thread,\
| | ... | 4 phy core, 2 receive queue per NIC port.
| | ... | [Ver] Find NDR for 64 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 64B | 4T4C | MTHREAD | NDRDISC
| | ...
| | [Template] | Find NDR for eth-l2xcbase-testpmd
| | wt=4 | rxq=2 | framesize=${64}

| tc14-64B-4t4c-eth-l2xcbase-testpmd-pdrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 4 thread,\
| | ... | 4 phy core, 2 receive queue per NIC port.
| | ... | [Ver] Find PDR for 64 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 64B | 4T4C | MTHREAD | PDRDISC | SKIP_PATCH
| | ...
| | [Template] | Find PDR for eth-l2xcbase-testpmd
| | wt=4 | rxq=2 | framesize=${64}

| tc15-1518B-4t4c-eth-l2xcbase-testpmd-ndrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 4 thread,\
| | ... | 4 phy core, 2 receive queue per NIC port.
| | ... | [Ver] Find NDR for 1518 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 1518B | 4T4C | MTHREAD | NDRDISC | SKIP_PATCH
| | ...
| | [Template] | Find NDR for eth-l2xcbase-testpmd
| | wt=4 | rxq=2 | framesize=${1518}

| tc16-1518B-4t4c-eth-l2xcbase-testpmd-pdrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 4 thread,\
| | ... | 4 phy core, 2 receive queue per NIC port.
| | ... | [Ver] Find PDR for 1518 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 1518B | 4T4C | MTHREAD | PDRDISC | SKIP_PATCH
| | ...
| | [Template] | Find PDR for eth-l2xcbase-testpmd
| | wt=4 | rxq=2 | framesize=${1518}

| tc17-9000B-4t4c-eth-l2xcbase-testpmd-ndrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 4 thread,\
| | ... | 4 phy core, 2 receive queue per NIC port.
| | ... | [Ver] Find NDR for 9000 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 9000B | 4T4C | MTHREAD | NDRDISC | SKIP_PATCH
| | ...
| | [Template] | Find NDR for eth-l2xcbase-testpmd
| | wt=4 | rxq=2 | framesize=${9000}

| tc18-9000B-4t4c-eth-l2xcbase-testpmd-pdrdisc
| | ...
| | [Documentation]
| | ... | [Cfg] DUT runs L2 frame forwarding config with 4 thread,\
| | ... | 4 phy core, 2 receive queue per NIC port.
| | ... | [Ver] Find PDR for 9000 Byte frames\
| | ... | using binary search, max 10GE linerate, step 100kpps.
| | ...
| | [Tags] | 9000B | 4T4C | MTHREAD | PDRDISC | SKIP_PATCH
| | ...
| | [Template] | Find PDR for eth-l2xcbase-testpmd
| | wt=4 | rxq=2 | framesize=${9000}
