---
# file: tasks/main.yml

- import_tasks: pre-setup.yml
  when:
    - calico_vm is defined
    - calico_sut is defined
  tags:
    - calico-pre-setup

- import_tasks: pre-action.yml
  when:
    - calico_metal is defined
    - calico_sut is defined
  tags:
    - calico-pre-action

- import_tasks: deploy.yml
  when:
    - calico_metal is defined
    - calico_sut is defined
  tags:
    - calico-deploy

- import_tasks: post-action.yml
  when:
    - calico_metal is defined
    - calico_sut is defined
  tags:
    - calico-post-action

- import_tasks: cleanup.yml
  when:
    - calico_metal is defined
    - calico_sut is defined
  tags:
    - calico-cleanup