---
name: "CSIT Fetch"
description: |
  Freshen existing local CSIT repository so oper branch detection works and checkout master.

inputs:
  path:
    description: "CSIT repository path to the pre-checkouted old clone of CSIT repo."
    required: true
    type: string
    default: "."

runs:
  using: "composite"
  steps:
    - name: Execute bash commands
      id: commands
      shell: bash
      env:
        GIT_URL: "https://github.com/FDio"
      run: |
        set -exuo pipe
        pushd ${{ inputs.path }}
        git fetch --all --depth=1 || echo "Continuing to restor cwd."
        git checkout master || echo "Continuing to restore cwd."
        popd
        # TODO: Copy outputs to LOG_DIR according to VPP practices.
