---
name: csit-hfr
run-name: csit-${{ github.event.inputs.dut }}-perf-report-${{ github.event.inputs.job_type }}-${{ github.event.inputs.branch == 'rls2602' && '2602' }}-${{ github.event.inputs.node }}-${{ github.event.inputs.my_run_id }}

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      job_type:
        description: "The type of job: iterative or coverage."
        required: true
        type: choice
        options:
          - iterative
          - coverage
        default: iterative
      dut:
        description: "CSIT test/ subdirectory containing suites to execute."
        required: true
        type: choice
        options:
          - dpdk
          - trex
          - vpp
        default: vpp
      node:
        description: Performance testbed node.
        required: true
        type: choice
        options:
          - 2n-aws
          - 2n-c6in
          - 2n-c7gn
          - 2n-c8gn
          - 2n-emr
          - 2n-grc
          - 2n-icx
          - 2n-spr
          - 2n-zn2
          - 3n-alt
          - 3n-emr
          - 3n-icx
          - 3n-oct
          - 3n-srf
          - 3na-spr
          - 3nb-spr
        default: 2n-emr
      branch:
        description: Branch or patch.
        required: true
        type: choice
        options:
          - rls2602
        default: rls2602
      suite_gen_params:
        description: Parameters for the suite generator.
        required: true
        type: string
      my_run_id:
        description: Run ID.
        required: true
        type: string

permissions:
  contents: read

jobs:
  dispatch:
    runs-on:
      - ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Prepare node selection matrix
        id: set-matrix
        uses: fdio/csit/.github/actions/csit-report-dispatch@9dfd78245563386a8b7d517345d3b0555a5d5a61
        with:
          node: ${{ github.event.inputs.node }}
          dut: ${{ github.event.inputs.dut }}

  csit-perf-report:
    needs: dispatch
    # yamllint disable-line rule:line-length
    name: csit-${{ github.event.inputs.dut }}-perf-report-${{ github.event.inputs.job_type }}-${{ github.event.inputs.branch == 'rls2602' && '2602' }}-${{ matrix.node }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=builder
      - fdio:size=csit
      - fdio:namespace=prod
      - fdio:os=${{ matrix.os }}
      - fdio:workflow=${{ github.run_id }}
    timeout-minutes: 1440

    strategy:
      matrix: ${{ fromJSON(needs.dispatch.outputs.matrix) }}

    env:
      # yamllint disable-line rule:line-length
      BUILD_TAG: csit-${{ github.event.inputs.dut }}-perf-report-${{ github.event.inputs.job_type }}-${{ github.event.inputs.branch == 'rls2602' && '2602' }}-${{ matrix.node }}-${{ github.run_id }}
      # yamllint disable-line rule:line-length
      JOB_NAME: csit-${{ github.event.inputs.dut }}-perf-report-${{ github.event.inputs.job_type }}-${{ github.event.inputs.branch == 'rls2602' && '2602' }}-${{ matrix.node }}
      GERRIT_BRANCH: ${{ github.event.inputs.branch }}
      TEST_TAG_STRING: ${{ github.event.inputs.suite_gen_params }}

    steps:
      - name: Git Checkout CSIT
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Setup Environment
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/setup-executor-env@b728d1589228e2891a4241a1bba362d76895c225

      - name: Run CSIT Bootstrap
        # yamllint disable-line rule:line-length
        uses: fdio/csit/.github/actions/csit-bootstrap@9dfd78245563386a8b7d517345d3b0555a5d5a61
        with:
          bootstrap_script: bootstrap_verify_perf.sh
          with_oper: false

      - name: AWS S3 Publish Logs
        shell: bash
        run: |
          echo ${BUILD_TAG}
          echo ${JOB_NAME}
          echo ${GERRIT_BRANCH}
          echo ${TEST_TAG_STRING}
